<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_StateMachine_Payment_Listener_AuditTrailService extends App_KernelTestContainer
{
    /*
     * Gets the private '.state_machine.payment.listener.audit_trail' shared service.
     *
     * @return \Symfony\Component\Workflow\EventListener\AuditTrailListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.state_machine.payment.listener.audit_trail'] = new \Symfony\Component\Workflow\EventListener\AuditTrailListener(($container->privates['monolog.logger.workflow'] ?? $container->load('getMonolog_Logger_WorkflowService')));
    }
}
