<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NchZeUVService extends App_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.NchZeUV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NchZeUV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'context' => ['privates', '.errored..service_locator.NchZeUV.Symfony\\Component\\Validator\\Context\\ExecutionContextInterface', NULL, 'Cannot autowire service ".service_locator.NchZeUV": it references interface "Symfony\\Component\\Validator\\Context\\ExecutionContextInterface" but no such service exists. Did you create an instantiable class that implements this interface?'],
        ], [
            'context' => 'Symfony\\Component\\Validator\\Context\\ExecutionContextInterface',
        ]);
    }
}
