<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8nqzJO3Service extends App_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.8nqzJO3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment_outbox' => ['privates', 'messenger.transport.payment_outbox', 'getMessenger_Transport_PaymentOutboxService', true],
            'payment_outbox_failed' => ['privates', 'messenger.transport.payment_outbox_failed', 'getMessenger_Transport_PaymentOutboxFailedService', true],
            'payment_events_in' => ['privates', 'messenger.transport.payment_events_in', 'getMessenger_Transport_PaymentEventsInService', true],
            'messenger.transport.payment_outbox' => ['privates', 'messenger.transport.payment_outbox', 'getMessenger_Transport_PaymentOutboxService', true],
            'messenger.transport.payment_outbox_failed' => ['privates', 'messenger.transport.payment_outbox_failed', 'getMessenger_Transport_PaymentOutboxFailedService', true],
            'messenger.transport.payment_events_in' => ['privates', 'messenger.transport.payment_events_in', 'getMessenger_Transport_PaymentEventsInService', true],
        ], [
            'payment_outbox' => '?',
            'payment_outbox_failed' => '?',
            'payment_events_in' => '?',
            'messenger.transport.payment_outbox' => '?',
            'messenger.transport.payment_outbox_failed' => '?',
            'messenger.transport.payment_events_in' => '?',
        ]);

        if (isset($container->privates['.service_locator.8nqzJO3'])) {
            return $container->privates['.service_locator.8nqzJO3'];
        }

        return $container->privates['.service_locator.8nqzJO3'] = $instance;
    }
}
