<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_NumTeF8Service extends App_KernelTestContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.NumTeF8' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.NumTeF8'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['console.messenger.execute_command_handler'] ?? $container->load('getConsole_Messenger_ExecuteCommandHandlerService')), ['sign' => true]);
    }
}
