<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S0MvCihService extends App_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.s0MvCih' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s0MvCih'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment_outbox_failed' => ['privates', 'messenger.transport.payment_outbox_failed', 'getMessenger_Transport_PaymentOutboxFailedService', true],
        ], [
            'payment_outbox_failed' => '?',
        ]);
    }
}
