<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Console_Command_WorkflowDump_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.console.command.workflow_dump.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.console.command.workflow_dump.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('workflow:dump', [], 'Dump a workflow', false, #[\Closure(name: 'console.command.workflow_dump', class: 'Symfony\\Component\\Workflow\\Command\\WorkflowDumpCommand')] fn (): \Symfony\Component\Workflow\Command\WorkflowDumpCommand => ($container->privates['console.command.workflow_dump'] ?? $container->load('getConsole_Command_WorkflowDumpService')));
    }
}
