<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Z51KjacService extends App_KernelTestContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.Z51Kjac' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.Z51Kjac'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['App\\Message\\Handler\\PaymentRefundHandler'] ?? $container->load('getPaymentRefundHandlerService')), []);
    }
}
