<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiErrorResponseFactoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\ApiErrorResponseFactory' shared autowired service.
     *
     * @return \App\Service\ApiErrorResponseFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ApiErrorResponseFactory'] = new \App\Service\ApiErrorResponseFactory();
    }
}
