<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRequestValidatorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\ApiRequestValidator' shared autowired service.
     *
     * @return \App\Service\ApiRequestValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ApiRequestValidator'] = new \App\Service\ApiRequestValidator(($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)), ($container->privates['App\\Service\\ValidationErrorMapper'] ??= new \App\Service\ValidationErrorMapper()));
    }
}
