<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircuitBreakerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\CircuitBreaker' shared autowired service.
     *
     * @return \App\Service\CircuitBreaker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\CircuitBreaker'] = new \App\Service\CircuitBreaker(($container->services['doctrine.dbal.data_connection'] ?? self::getDoctrine_Dbal_DataConnectionService($container)));
    }
}
