<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_WorkflowDumpService extends App_KernelTestContainer
{
    /*
     * Gets the private 'console.command.workflow_dump' shared service.
     *
     * @return \Symfony\Component\Workflow\Command\WorkflowDumpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['console.command.workflow_dump'] = $instance = new \Symfony\Component\Workflow\Command\WorkflowDumpCommand(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment' => ['privates', 'state_machine.payment', 'getStateMachine_PaymentService', false],
        ], [
            'payment' => 'Symfony\\Component\\Workflow\\StateMachine',
        ]));

        $instance->setName('workflow:dump');
        $instance->setDescription('Dump a workflow');

        return $instance;
    }
}
