<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Dbal_InfraSchemaAssetFilterManagerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'doctrine.dbal.infra_schema_asset_filter_manager' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Dbal\SchemaAssetsFilterManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['doctrine.dbal.infra_schema_asset_filter_manager'] = new \Doctrine\Bundle\DoctrineBundle\Dbal\SchemaAssetsFilterManager([($container->privates['doctrine_migrations.schema_filter_listener'] ??= new \Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener('doctrine_migration_versions'))]);
    }
}
