<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Dbal_IdleConnectionMiddleware_InfraService extends App_KernelTestContainer
{
    /*
     * Gets the private 'doctrine.dbal.idle_connection_middleware.infra' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Middleware\IdleConnectionMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.dbal.idle_connection_middleware.infra'] = $instance = new \Doctrine\Bundle\DoctrineBundle\Middleware\IdleConnectionMiddleware(($container->privates['doctrine.dbal.connection_expiries'] ??= new \ArrayObject()), ['data' => 600, 'infra' => 600]);

        $instance->setConnectionName('infra');

        return $instance;
    }
}
