<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Dbal_InfraConnectionService extends App_KernelTestContainer
{
    /*
     * Gets the public 'doctrine.dbal.infra_connection' shared service.
     *
     * @return \Doctrine\DBAL\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['doctrine.dbal.infra_connection'] = ($container->privates['doctrine.dbal.connection_factory'] ?? self::getDoctrine_Dbal_ConnectionFactoryService($container))->createConnection(['url' => $container->getEnv('resolve:INFRA_URL'), 'driver' => 'pdo_mysql', 'idle_connection_ttl' => 600, 'host' => 'localhost', 'port' => NULL, 'user' => 'root', 'password' => NULL, 'driverOptions' => [], 'defaultTableOptions' => []], ($container->privates['doctrine.dbal.infra_connection.configuration'] ?? $container->load('getDoctrine_Dbal_InfraConnection_ConfigurationService')), ($container->privates['doctrine.dbal.infra_connection.event_manager'] ?? $container->load('getDoctrine_Dbal_InfraConnection_EventManagerService')), []);
    }
}
