<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDlqReplayCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\DlqReplayCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\DlqReplayCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\DlqReplayCommand'] = $instance = new \App\Infrastructure\Console\DlqReplayCommand(($container->services['doctrine.dbal.data_connection'] ?? self::getDoctrine_Dbal_DataConnectionService($container)), ($container->privates['App\\Infrastructure\\OutboxPublisher'] ?? $container->load('getOutboxPublisherService')));

        $instance->setName('payment:dlq:replay');
        $instance->setDescription('Replay DLQ items back to outbox');

        return $instance;
    }
}
