<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDlqReplayCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\DlqReplayCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\DlqReplayCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:dlq:replay', [], 'Replay DLQ items back to outbox', false, #[\Closure(name: 'App\\Infrastructure\\Console\\DlqReplayCommand')] fn (): \App\Infrastructure\Console\DlqReplayCommand => ($container->privates['App\\Infrastructure\\Console\\DlqReplayCommand'] ?? $container->load('getDlqReplayCommandService')));
    }
}
