<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestContainer
{
    /*
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $instance->addFixtures([['fixture' => ($container->privates['App\\Infrastructure\\Fixture\\PaymentFixture'] ??= new \App\Infrastructure\Fixture\PaymentFixture()), 'groups' => []], ['fixture' => ($container->privates['App\\Infrastructure\\Fixture\\PaymentGatewayFixture'] ??= new \App\Infrastructure\Fixture\PaymentGatewayFixture()), 'groups' => []], ['fixture' => ($container->privates['App\\Infrastructure\\Fixture\\PaymentMethodFixture'] ??= new \App\Infrastructure\Fixture\PaymentMethodFixture()), 'groups' => []], ['fixture' => ($container->privates['App\\Infrastructure\\Fixture\\PaymentWebhookLogFixture'] ??= new \App\Infrastructure\Fixture\PaymentWebhookLogFixture()), 'groups' => []]]);

        return $instance;
    }
}
