<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDlqControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\DlqController' shared autowired service.
     *
     * @return \App\Controller\DlqController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\DlqController'] = new \App\Controller\DlqController(($container->privates['App\\Service\\DlqService'] ?? $container->load('getDlqServiceService')));
    }
}
