<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorHandler_ErrorRenderer_CliService extends App_KernelTestContainer
{
    /*
     * Gets the private 'error_handler.error_renderer.cli' shared service.
     *
     * @return \Symfony\Component\ErrorHandler\ErrorRenderer\CliErrorRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['error_handler.error_renderer.cli'] = new \Symfony\Component\ErrorHandler\ErrorRenderer\CliErrorRenderer();
    }
}
