<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecutionContextInterfaceService extends App_KernelTestContainer
{
    /*
     * Gets the private '.errored..service_locator.NchZeUV.Symfony\Component\Validator\Context\ExecutionContextInterface' shared service.
     *
     * @return \Symfony\Component\Validator\Context\ExecutionContextInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NchZeUV": it references interface "Symfony\\Component\\Validator\\Context\\ExecutionContextInterface" but no such service exists. Did you create an instantiable class that implements this interface?');
    }
}
