<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinalizeControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\FinalizeController' shared autowired service.
     *
     * @return \App\Controller\FinalizeController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\FinalizeController'] = new \App\Controller\FinalizeController(($container->privates['App\\Service\\ProviderGuard'] ?? $container->load('getProviderGuardService')), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Service\\ApiErrorResponseFactory'] ??= new \App\Service\ApiErrorResponseFactory()), ($container->privates['App\\Service\\ApiJsonBodyDecoder'] ??= new \App\Service\ApiJsonBodyDecoder()), ($container->privates['App\\Service\\ApiRequestValidator'] ?? $container->load('getApiRequestValidatorService')));
    }
}
