<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeGuesser_EnumTypeService extends App_KernelTestContainer
{
    /*
     * Gets the private 'form.type_guesser.enum_type' shared service.
     *
     * @return \Symfony\Component\Form\EnumFormTypeGuesser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.type_guesser.enum_type'] = new \Symfony\Component\Form\EnumFormTypeGuesser();
    }
}
