<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_CsrfService extends App_KernelTestContainer
{
    /*
     * Gets the private 'form.type_extension.csrf' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.type_extension.csrf'] = new \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension(($container->privates['security.csrf.token_manager'] ?? self::getSecurity_Csrf_TokenManagerService($container)), true, '_token', NULL, 'validators', ($container->privates['form.server_params'] ?? $container->load('getForm_ServerParamsService')), $container->parameters['form.type_extension.csrf.field_attr'], ['App\\Form\\PaymentConsoleFinalizeType' => NULL, 'App\\Form\\PaymentConsoleRefundType' => NULL, 'App\\Form\\PaymentCreateType' => NULL, 'App\\Form\\PaymentFinalizeType' => NULL, 'App\\Form\\PaymentStartType' => NULL]);
    }
}
