<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGateSloCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\GateSloCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\GateSloCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:gate:slo', [], 'Fail non-zero failures; print metrics', false, #[\Closure(name: 'App\\Infrastructure\\Console\\GateSloCommand')] fn (): \App\Infrastructure\Console\GateSloCommand => ($container->privates['App\\Infrastructure\\Console\\GateSloCommand'] ?? $container->load('getGateSloCommandService')));
    }
}
