<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGateSloCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\GateSloCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\GateSloCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\GateSloCommand'] = $instance = new \App\Infrastructure\Console\GateSloCommand(($container->privates['App\\Service\\Metric'] ??= new \App\Service\Metric()), ($container->services['doctrine.dbal.data_connection'] ?? self::getDoctrine_Dbal_DataConnectionService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setName('payment:gate:slo');
        $instance->setDescription('Fail non-zero failures; print metrics');

        return $instance;
    }
}
