<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdempotencyStoreInterfaceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\ServiceInterface\IdempotencyStoreInterface' shared autowired service.
     *
     * @return \App\ServiceInterface\IdempotencyStoreInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\ServiceInterface\\IdempotencyStoreInterface'] = ($container->privates['App\\Service\\IdempotencyStoreFactory'] ?? $container->load('getIdempotencyStoreFactoryService'))->create();
    }
}
