<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdempotencyServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\IdempotencyService' shared autowired service.
     *
     * @return \App\Service\IdempotencyService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\IdempotencyService'] = new \App\Service\IdempotencyService(($container->privates['App\\ServiceInterface\\IdempotencyStoreInterface'] ?? $container->load('getIdempotencyStoreInterfaceService')), $container->getEnv('int:default:payment.idem_ttl_default:IDEM_TTL'));
    }
}
