<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdemPurgeCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\IdemPurgeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\IdemPurgeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:idem:purge', [], 'Purge expired idempotency entries', false, #[\Closure(name: 'App\\Infrastructure\\Console\\IdemPurgeCommand')] fn (): \App\Infrastructure\Console\IdemPurgeCommand => ($container->privates['App\\Infrastructure\\Console\\IdemPurgeCommand'] ?? $container->load('getIdemPurgeCommandService')));
    }
}
