<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdemPurgeCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\IdemPurgeCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\IdemPurgeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\IdemPurgeCommand'] = $instance = new \App\Infrastructure\Console\IdemPurgeCommand(($container->privates['App\\ServiceInterface\\IdempotencyStoreInterface'] ?? $container->load('getIdempotencyStoreInterfaceService')));

        $instance->setName('payment:idem:purge');
        $instance->setDescription('Purge expired idempotency entries');

        return $instance;
    }
}
