<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_PaymentOutboxFailedService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.transport.payment_outbox_failed' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.payment_outbox_failed'])) {
            return $container->privates['messenger.transport.payment_outbox_failed'];
        }

        $instance = $a->createTransport('in-memory://', ['exchange' => ['name' => 'payment.events.dlq', 'type' => 'fanout'], 'queues' => ['payment_outbox_failed' => NULL], 'transport_name' => 'payment_outbox_failed'], ($container->privates['messenger.transport.native_php_serializer'] ?? $container->load('getMessenger_Transport_NativePhpSerializerService')));

        if (isset($container->privates['messenger.transport.payment_outbox_failed'])) {
            return $container->privates['messenger.transport.payment_outbox_failed'];
        }

        return $container->privates['messenger.transport.payment_outbox_failed'] = $instance;
    }
}
