<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Logger_PaymentAuditService extends App_KernelTestContainer
{
    /*
     * Gets the public 'monolog.logger.payment_audit' shared service.
     *
     * @return \Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['monolog.logger.payment_audit'] = $instance = new \Monolog\Logger('payment_audit');

        $instance->pushHandler(($container->privates['monolog.handler.payment_audit'] ?? $container->load('getMonolog_Handler_PaymentAuditService')));

        return $instance;
    }
}
