<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Failure_SendFailedMessageToFailureTransportListenerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.failure.send_failed_message_to_failure_transport_listener' shared service.
     *
     * @return \Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.failure.send_failed_message_to_failure_transport_listener'] = new \Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'payment_outbox' => ['privates', 'messenger.transport.payment_outbox_failed', 'getMessenger_Transport_PaymentOutboxFailedService', true],
            'payment_outbox_failed' => ['privates', 'messenger.transport.payment_outbox_failed', 'getMessenger_Transport_PaymentOutboxFailedService', true],
            'payment_events_in' => ['privates', 'messenger.transport.payment_outbox_failed', 'getMessenger_Transport_PaymentOutboxFailedService', true],
        ], [
            'payment_outbox' => '?',
            'payment_outbox_failed' => '?',
            'payment_events_in' => '?',
        ]), ($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')), ['payment_outbox' => 'payment_outbox_failed', 'payment_outbox_failed' => 'payment_outbox_failed', 'payment_events_in' => 'payment_outbox_failed']);
    }
}
