<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\MetricController' shared autowired service.
     *
     * @return \App\Controller\MetricController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\MetricController'] = new \App\Controller\MetricController(($container->privates['App\\Service\\Metric'] ??= new \App\Service\Metric()), ($container->privates['App\\Service\\ProjectionLagService'] ?? $container->load('getProjectionLagServiceService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
