<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_PaymentEventsInService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.transport.payment_events_in' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.payment_events_in'])) {
            return $container->privates['messenger.transport.payment_events_in'];
        }

        $instance = $a->createTransport('in-memory://', ['exchange' => ['name' => 'payment.events', 'type' => 'topic'], 'queues' => ['payment_events_in' => ['binding_keys' => ['payment.*']]], 'transport_name' => 'payment_events_in'], ($container->privates['messenger.transport.native_php_serializer'] ?? $container->load('getMessenger_Transport_NativePhpSerializerService')));

        if (isset($container->privates['messenger.transport.payment_events_in'])) {
            return $container->privates['messenger.transport.payment_events_in'];
        }

        return $container->privates['messenger.transport.payment_events_in'] = $instance;
    }
}
