<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Middleware_AddDefaultStampsMiddlewareService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.middleware.add_default_stamps_middleware' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\AddDefaultStampsMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.middleware.add_default_stamps_middleware'] = new \Symfony\Component\Messenger\Middleware\AddDefaultStampsMiddleware();
    }
}
