<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Listener_ResetMemoryUsageService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.listener.reset_memory_usage' shared service.
     *
     * @return \Symfony\Component\Messenger\EventListener\ResetMemoryUsageListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.listener.reset_memory_usage'] = new \Symfony\Component\Messenger\EventListener\ResetMemoryUsageListener();
    }
}
