<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_SendersLocatorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'messenger.senders_locator' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\Sender\SendersLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.8nqzJO3'] ?? $container->load('get_ServiceLocator_8nqzJO3Service'));

        if (isset($container->privates['messenger.senders_locator'])) {
            return $container->privates['messenger.senders_locator'];
        }

        $instance = new \Symfony\Component\Messenger\Transport\Sender\SendersLocator([], $a);

        if (isset($container->privates['messenger.senders_locator'])) {
            return $container->privates['messenger.senders_locator'];
        }

        return $container->privates['messenger.senders_locator'] = $instance;
    }
}
