<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricSubscriberService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\MetricSubscriber' shared autowired service.
     *
     * @return \App\Infrastructure\MetricSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Infrastructure\\MetricSubscriber'] = new \App\Infrastructure\MetricSubscriber(($container->privates['App\\Service\\Metric'] ??= new \App\Service\Metric()));
    }
}
