<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_Security_DefaultService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.describers.security.default' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\SecurityDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.describers.security.default'] = new \Nelmio\ApiDocBundle\Describer\SecurityDescriber([], ($container->privates['nelmio_api_doc.routes.default'] ?? $container->load('getNelmioApiDoc_Routes_DefaultService')), ($container->privates['nelmio_api_doc.controller_reflector'] ??= new \Nelmio\ApiDocBundle\Util\ControllerReflector($container)));
    }
}
