<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_RenderDocs_YamlService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.render_docs.yaml' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Render\Yaml\YamlOpenApiRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.render_docs.yaml'] = new \Nelmio\ApiDocBundle\Render\Yaml\YamlOpenApiRenderer();
    }
}
