<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Command_DumpService extends App_KernelTestContainer
{
    /*
     * Gets the public 'nelmio_api_doc.command.dump' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Command\DumpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['nelmio_api_doc.command.dump'] = $instance = new \Nelmio\ApiDocBundle\Command\DumpCommand(($container->services['nelmio_api_doc.render_docs'] ?? $container->load('getNelmioApiDoc_RenderDocsService')));

        $instance->setName('nelmio:apidoc:dump');

        return $instance;
    }
}
