<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Form_DocumentationExtensionService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.form.documentation_extension' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Form\Extension\DocumentationExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.form.documentation_extension'] = new \Nelmio\ApiDocBundle\Form\Extension\DocumentationExtension();
    }
}
