<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_TypeDescriber_TemplateService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.type_describer.template' shared service.
     *
     * @return \Nelmio\ApiDocBundle\TypeDescriber\TemplateDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['nelmio_api_doc.type_describer.chain'] ?? $container->load('getNelmioApiDoc_TypeDescriber_ChainService'));

        if (isset($container->privates['nelmio_api_doc.type_describer.template'])) {
            return $container->privates['nelmio_api_doc.type_describer.template'];
        }

        $instance = new \Nelmio\ApiDocBundle\TypeDescriber\TemplateDescriber($a);

        if (isset($container->privates['nelmio_api_doc.type_describer.template'])) {
            return $container->privates['nelmio_api_doc.type_describer.template'];
        }

        return $container->privates['nelmio_api_doc.type_describer.template'] = $instance;
    }
}
