<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_TypeDescriber_MixedService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.type_describer.mixed' shared service.
     *
     * @return \Nelmio\ApiDocBundle\TypeDescriber\MixedDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.type_describer.mixed'] = new \Nelmio\ApiDocBundle\TypeDescriber\MixedDescriber();
    }
}
