<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_TypeDescriber_ChainService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.type_describer.chain' shared service.
     *
     * @return \Nelmio\ApiDocBundle\TypeDescriber\ChainDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Nelmio\ApiDocBundle\TypeDescriber\ChainDescriber(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_api_doc.type_describer.nullable'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\NullableDescriber());
            yield 1 => ($container->privates['nelmio_api_doc.type_describer.array'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\ArrayDescriber());
            yield 2 => ($container->privates['nelmio_api_doc.type_describer.bool'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\BoolDescriber());
            yield 3 => ($container->privates['nelmio_api_doc.type_describer.class'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\ClassDescriber());
            yield 4 => ($container->privates['nelmio_api_doc.type_describer.dictionary'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\DictionaryDescriber());
            yield 5 => ($container->privates['nelmio_api_doc.type_describer.float'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\FloatDescriber());
            yield 6 => ($container->privates['nelmio_api_doc.type_describer.generic_class'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\GenericClassDescriber());
            yield 7 => ($container->privates['nelmio_api_doc.type_describer.generic_collection'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\GenericCollectionDescriber());
            yield 8 => ($container->privates['nelmio_api_doc.type_describer.integer'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\IntegerDescriber());
            yield 9 => ($container->privates['nelmio_api_doc.type_describer.intersection'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\IntersectionDescriber());
            yield 10 => ($container->privates['nelmio_api_doc.type_describer.list'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\ListDescriber());
            yield 11 => ($container->privates['nelmio_api_doc.type_describer.mixed'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\MixedDescriber());
            yield 12 => ($container->privates['nelmio_api_doc.type_describer.object'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\ObjectDescriber());
            yield 13 => ($container->privates['nelmio_api_doc.type_describer.string'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\StringDescriber());
            yield 14 => ($container->privates['nelmio_api_doc.type_describer.template'] ?? $container->load('getNelmioApiDoc_TypeDescriber_TemplateService'));
            yield 15 => ($container->privates['nelmio_api_doc.type_describer.union'] ??= new \Nelmio\ApiDocBundle\TypeDescriber\UnionDescriber());
        }, 16));

        if (isset($container->privates['nelmio_api_doc.type_describer.chain'])) {
            return $container->privates['nelmio_api_doc.type_describer.chain'];
        }

        return $container->privates['nelmio_api_doc.type_describer.chain'] = $instance;
    }
}
