<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNullOrderPaymentSyncService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\Order\NullOrderPaymentSync' shared autowired service.
     *
     * @return \App\Service\Order\NullOrderPaymentSync
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Order\\NullOrderPaymentSync'] = new \App\Service\Order\NullOrderPaymentSync(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
