<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_ModelDescribers_SelfDescribingService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.model_describers.self_describing' shared service.
     *
     * @return \Nelmio\ApiDocBundle\ModelDescriber\SelfDescribingModelDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.model_describers.self_describing'] = new \Nelmio\ApiDocBundle\ModelDescriber\SelfDescribingModelDescriber();
    }
}
