<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_OpenApi_GeneratorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.open_api.generator' shared service.
     *
     * @return \Nelmio\ApiDocBundle\OpenApiGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['nelmio_api_doc.open_api.generator'] = $instance = new \Nelmio\ApiDocBundle\OpenApiGenerator();

        $instance->addNelmioProcessor(($container->privates['nelmio_api_doc.swagger.processor.nullable_property'] ??= new \Nelmio\ApiDocBundle\Processor\NullablePropertyProcessor()), NULL);
        $instance->addNelmioProcessor(($container->privates['nelmio_api_doc.swagger.processor.map_query_string'] ??= new \Nelmio\ApiDocBundle\Processor\MapQueryStringProcessor()), NULL);
        $instance->addNelmioProcessor(($container->privates['nelmio_api_doc.swagger.processor.map_request_payload'] ??= new \Nelmio\ApiDocBundle\Processor\MapRequestPayloadProcessor()), NULL);

        return $instance;
    }
}
