<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_DefaultService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.describers.default' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\DefaultDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.describers.default'] = new \Nelmio\ApiDocBundle\Describer\DefaultDescriber();
    }
}
