<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_RenderDocs_HtmlService extends App_KernelTestContainer
{
    /*
     * Gets the private 'nelmio_api_doc.render_docs.html' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Render\Html\HtmlOpenApiRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.render_docs.html'] = new \Nelmio\ApiDocBundle\Render\Html\HtmlOpenApiRenderer(($container->privates['twig'] ?? self::getTwigService($container)), ['assets_mode' => 'cdn', 'swagger_ui_config' => [], 'redocly_config' => [], 'stoplight_config' => []]);
    }
}
