<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Controller_SwaggerJsonService extends App_KernelTestContainer
{
    /*
     * Gets the public 'nelmio_api_doc.controller.swagger_json' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Controller\DocumentationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['nelmio_api_doc.controller.swagger_json'] = new \Nelmio\ApiDocBundle\Controller\DocumentationController(($container->services['nelmio_api_doc.render_docs'] ?? $container->load('getNelmioApiDoc_RenderDocsService')));
    }
}
