<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutboxRunCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\OutboxRunCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\OutboxRunCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\OutboxRunCommand'] = $instance = new \App\Infrastructure\Console\OutboxRunCommand(($container->privates['App\\Infrastructure\\OutboxWorker'] ?? $container->load('getOutboxWorkerService')));

        $instance->setName('payment:outbox:run');
        $instance->setDescription('Publish outbox entries');

        return $instance;
    }
}
