<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutboxWorkerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\OutboxWorker' shared autowired service.
     *
     * @return \App\Infrastructure\OutboxWorker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Infrastructure\\OutboxWorker'] = new \App\Infrastructure\OutboxWorker(($container->services['doctrine.dbal.data_connection'] ?? self::getDoctrine_Dbal_DataConnectionService($container)), ($container->privates['App\\Infrastructure\\PublisherTransportLog'] ??= new \App\Infrastructure\PublisherTransportLog()), ($container->privates['App\\Infrastructure\\OutboxPublisher'] ?? $container->load('getOutboxPublisherService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
