<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutboxRunCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\OutboxRunCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\OutboxRunCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:outbox:run', [], 'Publish outbox entries', false, #[\Closure(name: 'App\\Infrastructure\\Console\\OutboxRunCommand')] fn (): \App\Infrastructure\Console\OutboxRunCommand => ($container->privates['App\\Infrastructure\\Console\\OutboxRunCommand'] ?? $container->load('getOutboxRunCommandService')));
    }
}
