<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentOutboxProcessorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\Outbox\PaymentOutboxProcessor' shared autowired service.
     *
     * @return \App\Service\Outbox\PaymentOutboxProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Outbox\\PaymentOutboxProcessor'] = new \App\Service\Outbox\PaymentOutboxProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['messenger.transport.payment_outbox'] ?? $container->load('getMessenger_Transport_PaymentOutboxService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
