<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalSignatureValidatorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\Webhook\PayPalSignatureValidator' shared autowired service.
     *
     * @return \App\Service\Webhook\PayPalSignatureValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Webhook\\PayPalSignatureValidator'] = new \App\Service\Webhook\PayPalSignatureValidator(($container->privates['App\\Service\\WebhookVerifier'] ??= new \App\Service\WebhookVerifier()));
    }
}
