<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentCreateTypeService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Form\PaymentCreateType' shared autowired service.
     *
     * @return \App\Form\PaymentCreateType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PaymentCreateType'] = new \App\Form\PaymentCreateType();
    }
}
