<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleFinalizeTypeService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Form\PaymentConsoleFinalizeType' shared autowired service.
     *
     * @return \App\Form\PaymentConsoleFinalizeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PaymentConsoleFinalizeType'] = new \App\Form\PaymentConsoleFinalizeType();
    }
}
