<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectionSyncService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\ProjectionSync' shared autowired service.
     *
     * @return \App\Service\ProjectionSync
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ProjectionSync'] = new \App\Service\ProjectionSync(($container->services['doctrine.dbal.data_connection'] ?? self::getDoctrine_Dbal_DataConnectionService($container)), ($container->privates['App\\Infrastructure\\PaymentProjectionRepository'] ?? $container->load('getPaymentProjectionRepositoryService')));
    }
}
