<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentE2eDemoCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Command\PaymentE2eDemoCommand' shared autowired service.
     *
     * @return \App\Command\PaymentE2eDemoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\PaymentE2eDemoCommand'] = $instance = new \App\Command\PaymentE2eDemoCommand();

        $instance->setName('payment:e2e:demo');
        $instance->setDescription('Demonstrates E2E flow: webhook -> outbox -> publish -> consume');

        return $instance;
    }
}
