<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PaymentService' shared autowired service.
     *
     * @return \App\Service\PaymentService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PaymentService'] = new \App\Service\PaymentService(($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')));
    }
}
