<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentFinalizeRequestDtovalidateStatusService extends App_KernelTestContainer
{
    /*
     * Gets the private '.service_locator.NchZeUV.App\Controller\Dto\PaymentFinalizeRequestDto::validateStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NchZeUV.App\\Controller\\Dto\\PaymentFinalizeRequestDto::validateStatus()'] = ($container->privates['.service_locator.NchZeUV'] ?? $container->load('get_ServiceLocator_NchZeUVService'))->withContext('App\\Controller\\Dto\\PaymentFinalizeRequestDto::validateStatus()', $container);
    }
}
