<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentRefundControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\PaymentRefundController' shared autowired service.
     *
     * @return \App\Controller\PaymentRefundController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\PaymentRefundController'] = new \App\Controller\PaymentRefundController(($container->privates['App\\Service\\RefundService'] ?? $container->load('getRefundServiceService')), ($container->privates['App\\Service\\ApiErrorResponseFactory'] ??= new \App\Service\ApiErrorResponseFactory()), ($container->privates['App\\Service\\ApiJsonBodyDecoder'] ??= new \App\Service\ApiJsonBodyDecoder()), ($container->privates['App\\Service\\ApiRequestValidator'] ?? $container->load('getApiRequestValidatorService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
