<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentProjectionRepositoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\PaymentProjectionRepository' shared autowired service.
     *
     * @return \App\Infrastructure\PaymentProjectionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Infrastructure\\PaymentProjectionRepository'] = new \App\Infrastructure\PaymentProjectionRepository(($container->services['doctrine.dbal.infra_connection'] ?? $container->load('getDoctrine_Dbal_InfraConnectionService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
