<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalWebhookControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\Webhook\PayPalWebhookController' shared autowired service.
     *
     * @return \App\Controller\Webhook\PayPalWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\Webhook\\PayPalWebhookController'] = new \App\Controller\Webhook\PayPalWebhookController(($container->privates['App\\Service\\Webhook\\PayPalSignatureValidator'] ?? $container->load('getPayPalSignatureValidatorService')), ($container->privates['App\\Service\\Webhook\\PayPalEventNormalizer'] ??= new \App\Service\Webhook\PayPalEventNormalizer()), ($container->privates['App\\Service\\Webhook\\JsonSchemaValidator'] ??= new \App\Service\Webhook\JsonSchemaValidator()), ($container->privates['App\\Service\\WebhookIngestService'] ?? $container->load('getWebhookIngestServiceService')), ($container->services['monolog.logger.payment_audit'] ?? $container->load('getMonolog_Logger_PaymentAuditService')));
    }
}
