<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleCreateHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PaymentConsoleCreateHandler' shared autowired service.
     *
     * @return \App\Service\PaymentConsoleCreateHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PaymentConsoleCreateHandler'] = new \App\Service\PaymentConsoleCreateHandler(($container->privates['App\\Service\\PaymentService'] ?? $container->load('getPaymentServiceService')));
    }
}
