<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentStartRequestDtoService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\Dto\PaymentStartRequestDto' shared autowired service.
     *
     * @return \App\Controller\Dto\PaymentStartRequestDto
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\Dto\\PaymentStartRequestDto'] = new \App\Controller\Dto\PaymentStartRequestDto();
    }
}
