<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectionRebuildCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\ProjectionRebuildCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\ProjectionRebuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\ProjectionRebuildCommand'] = $instance = new \App\Infrastructure\Console\ProjectionRebuildCommand(($container->privates['App\\Service\\ProjectionSync'] ?? $container->load('getProjectionSyncService')));

        $instance->setName('payment:projection:rebuild');
        $instance->setDescription('Rebuild full payment projection');

        return $instance;
    }
}
