<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleFinalizeHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PaymentConsoleFinalizeHandler' shared autowired service.
     *
     * @return \App\Service\PaymentConsoleFinalizeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PaymentConsoleFinalizeHandler'] = new \App\Service\PaymentConsoleFinalizeHandler(($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Service\\ProviderGuard'] ?? $container->load('getProviderGuardService')));
    }
}
