<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderGuardService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\ProviderGuard' shared autowired service.
     *
     * @return \App\Service\ProviderGuard
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ProviderGuard'] = new \App\Service\ProviderGuard(($container->privates['App\\Service\\ProviderRouter'] ?? $container->load('getProviderRouterService')), ($container->privates['App\\Service\\RetryExecutor'] ?? $container->load('getRetryExecutorService')), ($container->privates['App\\Service\\CircuitBreaker'] ?? $container->load('getCircuitBreakerService')), ($container->privates['App\\Service\\Metric'] ??= new \App\Service\Metric()));
    }
}
