<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentLifecycleCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\PaymentLifecycleCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\PaymentLifecycleCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\PaymentLifecycleCommand'] = $instance = new \App\Infrastructure\Console\PaymentLifecycleCommand(($container->privates['App\\Service\\PaymentService'] ?? $container->load('getPaymentServiceService')), ($container->privates['App\\Service\\PaymentStartService'] ?? $container->load('getPaymentStartServiceService')), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Service\\ProviderGuard'] ?? $container->load('getProviderGuardService')), ($container->privates['App\\Service\\RefundService'] ?? $container->load('getRefundServiceService')));

        $instance->setName('payment:lifecycle:run');

        return $instance;
    }
}
