<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleFinalizeRequestDtoService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\Dto\PaymentConsoleFinalizeRequestDto' shared autowired service.
     *
     * @return \App\Controller\Dto\PaymentConsoleFinalizeRequestDto
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\Dto\\PaymentConsoleFinalizeRequestDto'] = new \App\Controller\Dto\PaymentConsoleFinalizeRequestDto();
    }
}
