<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleRefundHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PaymentConsoleRefundHandler' shared autowired service.
     *
     * @return \App\Service\PaymentConsoleRefundHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PaymentConsoleRefundHandler'] = new \App\Service\PaymentConsoleRefundHandler(($container->privates['App\\Service\\RefundService'] ?? $container->load('getRefundServiceService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
