<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalPaymentProviderService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PayPalPaymentProvider' shared autowired service.
     *
     * @return \App\Service\PayPalPaymentProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PayPalPaymentProvider'] = new \App\Service\PayPalPaymentProvider(($container->privates['App\\Service\\Gateway\\PayPalGateway'] ??= new \App\Service\Gateway\PayPalGateway()));
    }
}
