<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectionSyncCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\ProjectionSyncCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\ProjectionSyncCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:projection:sync', [], 'Sync payment projection', false, #[\Closure(name: 'App\\Infrastructure\\Console\\ProjectionSyncCommand')] fn (): \App\Infrastructure\Console\ProjectionSyncCommand => ($container->privates['App\\Infrastructure\\Console\\ProjectionSyncCommand'] ?? $container->load('getProjectionSyncCommandService')));
    }
}
