<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentOutboxProcessCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Command\PaymentOutboxProcessCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\PaymentOutboxProcessCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:outbox:process', [], 'Publish payment outbox messages to RabbitMQ', false, #[\Closure(name: 'App\\Command\\PaymentOutboxProcessCommand')] fn (): \App\Command\PaymentOutboxProcessCommand => ($container->privates['App\\Command\\PaymentOutboxProcessCommand'] ?? $container->load('getPaymentOutboxProcessCommandService')));
    }
}
