<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentRefundHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Message\Handler\PaymentRefundHandler' shared autowired service.
     *
     * @return \App\Message\Handler\PaymentRefundHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Message\\Handler\\PaymentRefundHandler'] = new \App\Message\Handler\PaymentRefundHandler(($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->privates['App\\Service\\RefundService'] ?? $container->load('getRefundServiceService')));
    }
}
