<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderRouterService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\ProviderRouter' shared autowired service.
     *
     * @return \App\Service\ProviderRouter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ProviderRouter'] = new \App\Service\ProviderRouter(['internal' => ($container->privates['App\\Service\\InternalPaymentProvider'] ??= new \App\Service\InternalPaymentProvider()), 'stripe' => ($container->privates['App\\Service\\StripePaymentProvider'] ??= new \App\Service\StripePaymentProvider($container->getEnv('default::STRIPE_SECRET_KEY'), $container->getEnv('default::STRIPE_WEBHOOK_SECRET'))), 'paypal' => ($container->privates['App\\Service\\PayPalPaymentProvider'] ?? $container->load('getPayPalPaymentProviderService'))]);
    }
}
