<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentCreateHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Message\Handler\PaymentCreateHandler' shared autowired service.
     *
     * @return \App\Message\Handler\PaymentCreateHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Message\\Handler\\PaymentCreateHandler'] = new \App\Message\Handler\PaymentCreateHandler(($container->privates['App\\Service\\PaymentStartService'] ?? $container->load('getPaymentStartServiceService')));
    }
}
