<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentReadControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\PaymentReadController' shared autowired service.
     *
     * @return \App\Controller\PaymentReadController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\PaymentReadController'] = new \App\Controller\PaymentReadController(($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')));
    }
}
