<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleStartHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PaymentConsoleStartHandler' shared autowired service.
     *
     * @return \App\Service\PaymentConsoleStartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PaymentConsoleStartHandler'] = new \App\Service\PaymentConsoleStartHandler(($container->privates['App\\Service\\PaymentStartService'] ?? $container->load('getPaymentStartServiceService')));
    }
}
