<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentEventConsumerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Message\Handler\PaymentEventConsumer' shared autowired service.
     *
     * @return \App\Message\Handler\PaymentEventConsumer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Message\\Handler\\PaymentEventConsumer'] = new \App\Message\Handler\PaymentEventConsumer(($container->privates['App\\Service\\Reconciliation\\PaymentReconciliationService'] ?? $container->load('getPaymentReconciliationServiceService')), ($container->privates['App\\Service\\Order\\NullOrderPaymentSync'] ?? $container->load('getNullOrderPaymentSyncService')));
    }
}
