<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentConsoleControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\PaymentConsoleController' shared autowired service.
     *
     * @return \App\Controller\PaymentConsoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PaymentConsoleController'] = $instance = new \App\Controller\PaymentConsoleController(($container->privates['App\\Service\\PaymentConsoleCreateHandler'] ?? $container->load('getPaymentConsoleCreateHandlerService')), ($container->privates['App\\Service\\PaymentConsoleStartHandler'] ?? $container->load('getPaymentConsoleStartHandlerService')), ($container->privates['App\\Service\\PaymentConsoleReadModel'] ?? $container->load('getPaymentConsoleReadModelService')), ($container->privates['App\\Service\\PaymentConsoleFinalizeHandler'] ?? $container->load('getPaymentConsoleFinalizeHandlerService')), ($container->privates['App\\Service\\PaymentConsoleRefundHandler'] ?? $container->load('getPaymentConsoleRefundHandlerService')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'security.authorization_checker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'serializer' => '?',
            'security.authorization_checker' => '?',
            'twig' => '?',
            'form.factory' => '?',
            'security.token_storage' => '?',
            'security.csrf.token_manager' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\PaymentConsoleController', $container));

        return $instance;
    }
}
