<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentReconciliationServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\Reconciliation\PaymentReconciliationService' shared autowired service.
     *
     * @return \App\Service\Reconciliation\PaymentReconciliationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Reconciliation\\PaymentReconciliationService'] = new \App\Service\Reconciliation\PaymentReconciliationService(($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
