<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentOutboxProcessCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Command\PaymentOutboxProcessCommand' shared autowired service.
     *
     * @return \App\Command\PaymentOutboxProcessCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\PaymentOutboxProcessCommand'] = $instance = new \App\Command\PaymentOutboxProcessCommand(($container->privates['App\\Service\\Outbox\\PaymentOutboxProcessor'] ?? $container->load('getPaymentOutboxProcessorService')));

        $instance->setName('payment:outbox:process');
        $instance->setDescription('Publish payment outbox messages to RabbitMQ');

        return $instance;
    }
}
