<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentE2eDemoCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Command\PaymentE2eDemoCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\PaymentE2eDemoCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:e2e:demo', [], 'Demonstrates E2E flow: webhook -> outbox -> publish -> consume', false, #[\Closure(name: 'App\\Command\\PaymentE2eDemoCommand')] fn (): \App\Command\PaymentE2eDemoCommand => ($container->privates['App\\Command\\PaymentE2eDemoCommand'] ?? $container->load('getPaymentE2eDemoCommandService')));
    }
}
