<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectionRebuildCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\ProjectionRebuildCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\ProjectionRebuildCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:projection:rebuild', [], 'Rebuild full payment projection', false, #[\Closure(name: 'App\\Infrastructure\\Console\\ProjectionRebuildCommand')] fn (): \App\Infrastructure\Console\ProjectionRebuildCommand => ($container->privates['App\\Infrastructure\\Console\\ProjectionRebuildCommand'] ?? $container->load('getProjectionRebuildCommandService')));
    }
}
