<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentApiStartHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\PaymentApiStartHandler' shared autowired service.
     *
     * @return \App\Service\PaymentApiStartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PaymentApiStartHandler'] = new \App\Service\PaymentApiStartHandler(($container->privates['App\\Service\\PaymentStartService'] ?? $container->load('getPaymentStartServiceService')), ($container->privates['App\\Service\\IdempotencyService'] ?? $container->load('getIdempotencyServiceService')));
    }
}
