<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentMethodFixtureService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Fixture\PaymentMethodFixture' shared autowired service.
     *
     * @return \App\Infrastructure\Fixture\PaymentMethodFixture
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Infrastructure\\Fixture\\PaymentMethodFixture'] = new \App\Infrastructure\Fixture\PaymentMethodFixture();
    }
}
