<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\RefundService' shared autowired service.
     *
     * @return \App\Service\RefundService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\RefundService'] = new \App\Service\RefundService(($container->privates['App\\Service\\ProviderGuard'] ?? $container->load('getProviderGuardService')), ($container->privates['App\\Repository\\PaymentRepository'] ?? $container->load('getPaymentRepositoryService')));
    }
}
