<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouting_Loader_Attribute_ServicesService extends App_KernelTestContainer
{
    /*
     * Gets the private 'routing.loader.attribute.services' shared service.
     *
     * @return \Symfony\Component\Routing\Loader\AttributeServicesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['routing.loader.attribute.services'] = new \Symfony\Component\Routing\Loader\AttributeServicesLoader([]);
    }
}
