<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRetryExecutorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\RetryExecutor' shared autowired service.
     *
     * @return \App\Service\RetryExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\RetryExecutor'] = new \App\Service\RetryExecutor(($container->privates['App\\Service\\Metric'] ??= new \App\Service\Metric()));
    }
}
