<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReconcileRunCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\ReconcileRunCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\ReconcileRunCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:reconcile:run', [], 'Reconcile all processing payments', false, #[\Closure(name: 'App\\Infrastructure\\Console\\ReconcileRunCommand')] fn (): \App\Infrastructure\Console\ReconcileRunCommand => ($container->privates['App\\Infrastructure\\Console\\ReconcileRunCommand'] ?? $container->load('getReconcileRunCommandService')));
    }
}
