<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReconcileRunCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\ReconcileRunCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\ReconcileRunCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\ReconcileRunCommand'] = $instance = new \App\Infrastructure\Console\ReconcileRunCommand(($container->privates['App\\Service\\ReconciliationService'] ?? $container->load('getReconciliationServiceService')));

        $instance->setName('payment:reconcile:run');
        $instance->setDescription('Reconcile all processing payments');

        return $instance;
    }
}
