<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripePaymentProviderService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\StripePaymentProvider' shared autowired service.
     *
     * @return \App\Service\StripePaymentProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\StripePaymentProvider'] = new \App\Service\StripePaymentProvider($container->getEnv('default::STRIPE_SECRET_KEY'), $container->getEnv('default::STRIPE_WEBHOOK_SECRET'));
    }
}
