<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlaReportCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Console\SlaReportCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\SlaReportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Infrastructure\\Console\\SlaReportCommand'] = $instance = new \App\Infrastructure\Console\SlaReportCommand(($container->privates['App\\Service\\SlaReporter'] ?? $container->load('getSlaReporterService')));

        $instance->setName('payment:sla:report');
        $instance->setDescription('Print SLA stats for window');

        return $instance;
    }
}
