<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlaReportCommand_LazyService extends App_KernelTestContainer
{
    /*
     * Gets the private '.App\Infrastructure\Console\SlaReportCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Infrastructure\\Console\\SlaReportCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('payment:sla:report', [], 'Print SLA stats for window', false, #[\Closure(name: 'App\\Infrastructure\\Console\\SlaReportCommand')] fn (): \App\Infrastructure\Console\SlaReportCommand => ($container->privates['App\\Infrastructure\\Console\\SlaReportCommand'] ?? $container->load('getSlaReportCommandService')));
    }
}
