<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlaReporterService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\SlaReporter' shared autowired service.
     *
     * @return \App\Service\SlaReporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SlaReporter'] = new \App\Service\SlaReporter(($container->services['doctrine.dbal.data_connection'] ?? self::getDoctrine_Dbal_DataConnectionService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
