<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_PaymentMemoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'security.user.provider.concrete.payment_memory' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\InMemoryUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.user.provider.concrete.payment_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([]);
    }
}
