<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStartControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\StartController' shared autowired service.
     *
     * @return \App\Controller\StartController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\StartController'] = new \App\Controller\StartController(($container->privates['App\\Service\\PaymentApiStartHandler'] ?? $container->load('getPaymentApiStartHandlerService')), ($container->privates['App\\Service\\ApiErrorResponseFactory'] ??= new \App\Service\ApiErrorResponseFactory()), ($container->privates['App\\Service\\ApiJsonBodyDecoder'] ??= new \App\Service\ApiJsonBodyDecoder()), ($container->privates['App\\Service\\ApiRequestValidator'] ?? $container->load('getApiRequestValidatorService')));
    }
}
