<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeEventNormalizerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\Webhook\StripeEventNormalizer' shared autowired service.
     *
     * @return \App\Service\Webhook\StripeEventNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Webhook\\StripeEventNormalizer'] = new \App\Service\Webhook\StripeEventNormalizer();
    }
}
