<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeWebhookControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\Webhook\StripeWebhookController' shared autowired service.
     *
     * @return \App\Controller\Webhook\StripeWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\Webhook\\StripeWebhookController'] = new \App\Controller\Webhook\StripeWebhookController(($container->privates['App\\Service\\Webhook\\StripeSignatureValidator'] ?? $container->load('getStripeSignatureValidatorService')), ($container->privates['App\\Service\\Webhook\\StripeEventNormalizer'] ??= new \App\Service\Webhook\StripeEventNormalizer()), ($container->privates['App\\Service\\Webhook\\JsonSchemaValidator'] ??= new \App\Service\Webhook\JsonSchemaValidator()), ($container->privates['App\\Service\\WebhookIngestService'] ?? $container->load('getWebhookIngestServiceService')), ($container->services['monolog.logger.payment_audit'] ?? $container->load('getMonolog_Logger_PaymentAuditService')));
    }
}
