<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookVerifierService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\WebhookVerifier' shared autowired service.
     *
     * @return \App\Service\WebhookVerifier
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\WebhookVerifier'] = new \App\Service\WebhookVerifier();
    }
}
