<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\WebhookController' shared autowired service.
     *
     * @return \App\Controller\WebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\WebhookController'] = new \App\Controller\WebhookController(($container->privates['App\\Service\\WebhookVerifier'] ??= new \App\Service\WebhookVerifier()), ($container->privates['App\\Service\\ProviderGuard'] ?? $container->load('getProviderGuardService')), ($container->privates['App\\Service\\ApiJsonBodyDecoder'] ??= new \App\Service\ApiJsonBodyDecoder()), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Service\\Mapper\\AdyenEventMapper'] ??= new \App\Service\Mapper\AdyenEventMapper());
            yield 1 => ($container->privates['App\\Service\\Mapper\\StripeEventMapper'] ??= new \App\Service\Mapper\StripeEventMapper());
        }, 2), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
