<?php

namespace ContainerLUyKJQj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookIngestServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\WebhookIngestService' shared autowired service.
     *
     * @return \App\Service\WebhookIngestService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\WebhookIngestService'] = new \App\Service\WebhookIngestService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
