services:
  # Handlers & processors
  OrderComponent\Payment\Message\Handler\Payment\PaymentCreateHandler:
    arguments:
      $gateways: !tagged_iterator payment.gateway
    tags: ['messenger.message_handler']

  OrderComponent\Payment\Message\Handler\Payment\PaymentRefundHandler:
    arguments:
      $gateways: !tagged_iterator payment.gateway
    tags: ['messenger.message_handler']

  OrderComponent\Payment\Api\Processor\PaymentCreateProcessor: ~
  OrderComponent\Payment\Api\Processor\PaymentRefundProcessor: ~

  # Gateways
  OrderComponent\Payment\Service\Payment\Gateway\StripeGateway:
    tags: ['payment.gateway']

  OrderComponent\Payment\Service\Payment\Gateway\PayPalGateway:
    tags: ['payment.gateway']