paying:
  app_secret: '%env(APP_SECRET)%'
  storage:
    data_url: '%env(resolve:DATABASE_URL)%'
    data_server_version: '16.0'
    infra_url: '%env(resolve:INFRA_URL)%'
    infra_server_version: '3.45.1'
  messenger:
    dsn: '%env(resolve:RABBITMQ_DSN)%'
  provider:
    default_provider: 'manual'
    stripe_secret_key: '%env(default::STRIPE_SECRET_KEY)%'
    stripe_webhook_secret: '%env(default::STRIPE_WEBHOOK_SECRET)%'
    payment_success_url: '%env(default::PAYMENT_SUCCESS_URL)%'
    payment_cancel_url: '%env(default::PAYMENT_CANCEL_URL)%'
  idempotency:
    ttl_sec: '%env(int:default:payment.idem_ttl_default:IDEM_TTL)%'
    redis_url: '%env(default::REDIS_URL)%'
  oidc:
    disabled: '%env(bool:default::OIDC_DISABLED)%'
    issuer: '%env(default::OIDC_ISS)%'
    audience: '%env(default::OIDC_AUD)%'
    jwks_url: '%env(default::OIDC_JWKS_URL)%'
    jwks_ttl: '%env(int:default::OIDC_JWKS_TTL)%'
  webhook:
    allow_unknown: '%env(bool:default::PAYMENT_WEBHOOK_ALLOW_UNKNOWN)%'
    adyen_hmac_secret: '%env(default::ADYEN_HMAC_SECRET)%'
