framework:
  messenger:
    transports:
      payment_events_in:
        dsn: '%paying.messenger.dsn%'
        options:
          exchange:
            name: 'payment.events'
            type: 'topic'
          queues:
            payment_events_in:
              binding_keys: [ 'payment.*' ]
