<?php

declare(strict_types=1);

namespace App\Paying\Migrations\Baseline;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260915190000CurrentBaseline extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Materialize the current Paying ORM baseline for missing Paying-owned tables.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Paying baseline supports PostgreSQL only.');
        $tables = [
            'payment_dlq',
            'payment_gateway',
            'payment_method',
            'payment_outbox_message',
            'payment_recurring',
            'payment_refund',
            'payment_token',
            'payment_transaction',
            'payment_translation',
            'payment_webhook_log',
        ];
        $existing = array_values(array_filter($tables, static fn (string $table): bool => $schema->hasTable($table)));
        if (count($existing) === count($tables)) { return; }
        $this->abortIf([] !== $existing, sprintf('Partial Paying baseline detected (%d/%d tables); refusing mixed create/adopt execution.', count($existing), count($tables)));

        $this->addSql('CREATE TABLE payment_dlq (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, outbox_id UUID NOT NULL, topic VARCHAR(128) NOT NULL, payload JSON NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE payment_gateway (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, code VARCHAR(32) NOT NULL, currencies JSON DEFAULT NULL, sandbox_mode BOOLEAN DEFAULT false NOT NULL, logo_url VARCHAR(255) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DB7D395989D9B62 ON payment_gateway (slug)');
        $this->addSql('CREATE TABLE payment_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, code VARCHAR(32) NOT NULL, method_name VARCHAR(100) DEFAULT NULL, gateway_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B61A1F6989D9B62 ON payment_method (slug)');
        $this->addSql('CREATE INDEX IDX_7B61A1F6577F8E00 ON payment_method (gateway_id)');
        $this->addSql('CREATE TABLE payment_outbox_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, type VARCHAR(128) NOT NULL, payload JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT \'pending\' NOT NULL, attempts INT DEFAULT 0 NOT NULL, last_error TEXT DEFAULT NULL, routing_key VARCHAR(128) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AAB592A2989D9B62 ON payment_outbox_message (slug)');
        $this->addSql('CREATE TABLE payment_recurring (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subscription_id VARCHAR(128) DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, transaction_id VARCHAR(64) DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, status VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F452DC5D17F50A6 ON payment_recurring (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F452DC5989D9B62 ON payment_recurring (slug)');
        $this->addSql('CREATE TABLE payment_refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, payment_id UUID NOT NULL, amount_minor INT NOT NULL, currency VARCHAR(3) NOT NULL, reason VARCHAR(64) DEFAULT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7E148FCE989D9B62 ON payment_refund (slug)');
        $this->addSql('CREATE TABLE payment_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(191) DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_by VARCHAR(190) DEFAULT NULL, method_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87E9789D17F50A6 ON payment_token (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87E9789989D9B62 ON payment_token (slug)');
        $this->addSql('CREATE INDEX IDX_87E978919883967 ON payment_token (method_id)');
        $this->addSql('CREATE TABLE payment_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, payment_id UUID NOT NULL, gateway_transaction_id VARCHAR(64) NOT NULL, type VARCHAR(16) NOT NULL, amount_minor INT NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84BBD50B989D9B62 ON payment_transaction (slug)');
        $this->addSql('CREATE TABLE payment_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(16) NOT NULL, title VARCHAR(160) DEFAULT NULL, description TEXT DEFAULT NULL, uuid BYTEA NOT NULL, slug VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, payment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42E595B5D17F50A6 ON payment_translation (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42E595B5989D9B62 ON payment_translation (slug)');
        $this->addSql('CREATE INDEX IDX_42E595B54C3A3BB ON payment_translation (payment_id)');
        $this->addSql('CREATE TABLE payment_webhook_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug UUID NOT NULL, provider VARCHAR(32) NOT NULL, external_event_id VARCHAR(191) NOT NULL, payload JSON NOT NULL, status VARCHAR(16) NOT NULL, duplicate_count INT DEFAULT 0 NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_85E992A2989D9B62 ON payment_webhook_log (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_payment_webhook_provider_event ON payment_webhook_log (provider, external_event_id)');
        $this->addSql('ALTER TABLE payment_method ADD CONSTRAINT FK_7B61A1F6577F8E00 FOREIGN KEY (gateway_id) REFERENCES payment_gateway (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_token ADD CONSTRAINT FK_87E978919883967 FOREIGN KEY (method_id) REFERENCES payment_method (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_translation ADD CONSTRAINT FK_42E595B54C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Current Paying ORM baseline is the forward schema contract.');
    }
}
