imports:
    - { resource: 'services/payment_aliases.yaml' }

parameters:
    payment.idem_ttl_default: 86400
    paying.messenger.dsn: '%env(resolve:RABBITMQ_DSN)%'
    paying.storage.data_server_version: '16.0'
    paying.storage.infra_server_version: '3.45.1'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\ServiceInterface\EventMapperInterface:
            tags: [ 'payment.event_mapper' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/**/Resources/'
            - '../src/**/Tests/'

    App\ServiceInterface\IdempotencyStoreInterface:
        factory: [ '@App\Service\IdempotencyStoreFactory', 'create' ]

    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: [ 'controller.service_arguments' ]

    App\Service\ProviderRouter:
        arguments:
            $providers:
                internal: '@App\Service\InternalPaymentProvider'
                stripe: '@App\Service\StripePaymentProvider'
                paypal: '@App\Service\PayPalPaymentProvider'

    App\Service\StripePaymentProvider:
        arguments:
            $secretKey: '%env(default::STRIPE_SECRET_KEY)%'
            $webhookSecret: '%env(default::STRIPE_WEBHOOK_SECRET)%'


    App\Service\IdempotencyService:
        arguments:
            $ttlSec: '%env(int:default:payment.idem_ttl_default:IDEM_TTL)%'

    App\Infrastructure\PaymentProjectionRepository:
        arguments:
            $infra: '@doctrine.dbal.infra_connection'

    App\Infrastructure\RateLimitSubscriber:
        arguments:
            $paymentApiLimiter: '@limiter.payment_api'

    App\Controller\WebhookController:
        public: true
        tags: [ 'controller.service_arguments' ]
        arguments:
            $mappers: !tagged_iterator payment.event_mapper

    payment_audit.logger:
        alias: monolog.logger.payment_audit

    App\Controller\Webhook\StripeWebhookController:
        public: true
        tags: [ 'controller.service_arguments' ]
        arguments:
            $paymentAuditLogger: '@payment_audit.logger'

    App\Controller\Webhook\PayPalWebhookController:
        public: true
        tags: [ 'controller.service_arguments' ]
        arguments:
            $paymentAuditLogger: '@payment_audit.logger'

    App\Service\Outbox\PaymentOutboxProcessor:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $transport: '@messenger.transport.payment_outbox'
            $logger: '@logger'

    App\Service\Order\NullOrderPaymentSync:
        arguments:
            $logger: '@logger'
        autoconfigure: true
        autowire: true

