<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLUyKJQj\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLUyKJQj/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerLUyKJQj.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerLUyKJQj\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerLUyKJQj\App_KernelTestContainer([
    'container.build_hash' => 'LUyKJQj',
    'container.build_id' => 'cf060300',
    'container.build_time' => 1775181317,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLUyKJQj');
