payment_webhook:
  path: /payment/webhook/{provider}
  controller: App\Paying\Controller\WebhookController::webhook
  methods: [ POST ]

payment_webhook_stripe:
  path: /webhook/stripe
  controller: App\Paying\Controller\Webhook\StripeWebhookController::__invoke
  methods: [ POST ]

payment_webhook_paypal:
  path: /webhook/paypal
  controller: App\Paying\Controller\Webhook\PayPalWebhookController::__invoke
  methods: [ POST ]
