payment_api_doc_json:
  path: /api/docs.json
  methods: [ GET ]
  defaults:
    _controller: nelmio_api_doc.controller.swagger

payment_api_doc_ui:
  path: /api/docs
  methods: [ GET ]
  defaults:
    _controller: nelmio_api_doc.controller.swagger_ui
