<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Payment__CLASSMETADATA__' => 0,
'App__Entity__PaymentWebhookLog__CLASSMETADATA__' => 1,
'App__Entity__PaymentGateway__CLASSMETADATA__' => 2,
'App__Entity__PaymentMethod__CLASSMETADATA__' => 3,
'App__Entity__PaymentOutboxMessage__CLASSMETADATA__' => 4,
'App__Entity__PaymentRefund__CLASSMETADATA__' => 5,
'App__Entity__PaymentTransaction__CLASSMETADATA__' => 6,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\Payment',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Payment',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'ulid',
                        'scale' => null,
                        'length' => null,
                        'unique' => true,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'orderId' => [
                        'fieldName' => 'orderId',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 128,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'order_id',
                    ],
                    'status' => [
                        'fieldName' => 'status',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 16,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'enumType' => 'App\\ValueObject\\PaymentStatus',
                        'columnName' => 'status',
                    ],
                    'amount' => [
                        'fieldName' => 'amount',
                        'type' => 'decimal',
                        'scale' => 2,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => 14,
                        'columnName' => 'amount',
                    ],
                    'currency' => [
                        'fieldName' => 'currency',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 3,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'currency',
                    ],
                    'providerRef' => [
                        'fieldName' => 'providerRef',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 128,
                        'unique' => false,
                        'nullable' => true,
                        'precision' => null,
                        'columnName' => 'provider_ref',
                    ],
                    'createdAt' => [
                        'fieldName' => 'createdAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'created_at',
                    ],
                    'updatedAt' => [
                        'fieldName' => 'updatedAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'updated_at',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'order_id' => 'orderId',
                    'status' => 'status',
                    'amount' => 'amount',
                    'currency' => 'currency',
                    'provider_ref' => 'providerRef',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'orderId' => 'order_id',
                    'status' => 'status',
                    'amount' => 'amount',
                    'currency' => 'currency',
                    'providerRef' => 'provider_ref',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'preUpdate' => [
                        'touch',
                    ],
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\PaymentWebhookLog',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PaymentWebhookLog',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'provider' => [
                        'fieldName' => 'provider',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 32,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'provider',
                    ],
                    'externalEventId' => [
                        'fieldName' => 'externalEventId',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 191,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'external_event_id',
                    ],
                    'payload' => [
                        'fieldName' => 'payload',
                        'type' => 'json',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'payload',
                    ],
                    'status' => [
                        'fieldName' => 'status',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 16,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'status',
                    ],
                    'duplicateCount' => [
                        'fieldName' => 'duplicateCount',
                        'type' => 'integer',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'options' => [
                            'default' => 0,
                        ],
                        'columnName' => 'duplicate_count',
                    ],
                    'receivedAt' => [
                        'fieldName' => 'receivedAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'received_at',
                    ],
                    'processedAt' => [
                        'fieldName' => 'processedAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => true,
                        'precision' => null,
                        'columnName' => 'processed_at',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'provider' => 'provider',
                    'external_event_id' => 'externalEventId',
                    'payload' => 'payload',
                    'status' => 'status',
                    'duplicate_count' => 'duplicateCount',
                    'received_at' => 'receivedAt',
                    'processed_at' => 'processedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'provider' => 'provider',
                    'externalEventId' => 'external_event_id',
                    'payload' => 'payload',
                    'status' => 'status',
                    'duplicateCount' => 'duplicate_count',
                    'receivedAt' => 'received_at',
                    'processedAt' => 'processed_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment_webhook_log',
                    'uniqueConstraints' => [
                        'uniq_payment_webhook_provider_event' => [
                            'columns' => [
                                'provider',
                                'external_event_id',
                            ],
                        ],
                    ],
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\PaymentGateway',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PaymentGateway',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'code' => [
                        'fieldName' => 'code',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 32,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'code',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'code' => 'code',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'code' => 'code',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment_gateway',
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\PaymentMethod',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PaymentMethod',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'code' => [
                        'fieldName' => 'code',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 32,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'code',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'code' => 'code',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'code' => 'code',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment_method',
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\PaymentOutboxMessage',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PaymentOutboxMessage',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'type' => [
                        'fieldName' => 'type',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 128,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'type',
                    ],
                    'payload' => [
                        'fieldName' => 'payload',
                        'type' => 'json',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'payload',
                    ],
                    'occurredAt' => [
                        'fieldName' => 'occurredAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'occurred_at',
                    ],
                    'status' => [
                        'fieldName' => 'status',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 32,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'options' => [
                            'default' => 'pending',
                        ],
                        'columnName' => 'status',
                    ],
                    'attempts' => [
                        'fieldName' => 'attempts',
                        'type' => 'integer',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'options' => [
                            'default' => 0,
                        ],
                        'columnName' => 'attempts',
                    ],
                    'lastError' => [
                        'fieldName' => 'lastError',
                        'type' => 'text',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => true,
                        'precision' => null,
                        'columnName' => 'last_error',
                    ],
                    'routingKey' => [
                        'fieldName' => 'routingKey',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 128,
                        'unique' => false,
                        'nullable' => true,
                        'precision' => null,
                        'columnName' => 'routing_key',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'payload' => 'payload',
                    'occurred_at' => 'occurredAt',
                    'status' => 'status',
                    'attempts' => 'attempts',
                    'last_error' => 'lastError',
                    'routing_key' => 'routingKey',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'type' => 'type',
                    'payload' => 'payload',
                    'occurredAt' => 'occurred_at',
                    'status' => 'status',
                    'attempts' => 'attempts',
                    'lastError' => 'last_error',
                    'routingKey' => 'routing_key',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment_outbox_message',
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\PaymentRefund',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PaymentRefund',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'paymentId' => [
                        'fieldName' => 'paymentId',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'payment_id',
                    ],
                    'amountMinor' => [
                        'fieldName' => 'amountMinor',
                        'type' => 'integer',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'amount_minor',
                    ],
                    'currency' => [
                        'fieldName' => 'currency',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 3,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'currency',
                    ],
                    'reason' => [
                        'fieldName' => 'reason',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 64,
                        'unique' => false,
                        'nullable' => true,
                        'precision' => null,
                        'columnName' => 'reason',
                    ],
                    'refundedAt' => [
                        'fieldName' => 'refundedAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'refunded_at',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'payment_id' => 'paymentId',
                    'amount_minor' => 'amountMinor',
                    'currency' => 'currency',
                    'reason' => 'reason',
                    'refunded_at' => 'refundedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'paymentId' => 'payment_id',
                    'amountMinor' => 'amount_minor',
                    'currency' => 'currency',
                    'reason' => 'reason',
                    'refundedAt' => 'refunded_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment_refund',
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'name' => [
                'App\\Entity\\PaymentTransaction',
            ],
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\PaymentTransaction',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'fieldMappings' => [
                [
                    'id' => [
                        'fieldName' => 'id',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'id' => true,
                        'columnName' => 'id',
                    ],
                    'paymentId' => [
                        'fieldName' => 'paymentId',
                        'type' => 'guid',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'payment_id',
                    ],
                    'gatewayTransactionId' => [
                        'fieldName' => 'gatewayTransactionId',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 64,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'gateway_transaction_id',
                    ],
                    'type' => [
                        'fieldName' => 'type',
                        'type' => 'string',
                        'scale' => null,
                        'length' => 16,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'type',
                    ],
                    'amountMinor' => [
                        'fieldName' => 'amountMinor',
                        'type' => 'integer',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'amount_minor',
                    ],
                    'occurredAt' => [
                        'fieldName' => 'occurredAt',
                        'type' => 'datetime_immutable',
                        'scale' => null,
                        'length' => null,
                        'unique' => false,
                        'nullable' => false,
                        'precision' => null,
                        'columnName' => 'occurred_at',
                    ],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'payment_id' => 'paymentId',
                    'gateway_transaction_id' => 'gatewayTransactionId',
                    'type' => 'type',
                    'amount_minor' => 'amountMinor',
                    'occurred_at' => 'occurredAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'paymentId' => 'payment_id',
                    'gatewayTransactionId' => 'gateway_transaction_id',
                    'type' => 'type',
                    'amountMinor' => 'amount_minor',
                    'occurredAt' => 'occurred_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment_transaction',
                ],
            ],
            'idGenerator' => [
                $o[1],
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
